name: Hello GitHub Actions

on: 
  push:


jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          
      - name: Installation
        run: npm install
      
      - name: Run
        run: npm run build

      - name: Start
        run: |
          nohup npm start &
          sleep 5

      - name: Test
        run: npm test
