name: Hello GitHub Actions

on: workflow_dispatch

env:
  BASE_URL: "https://example.com/api"

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Installation
        run: npm install
      
      - name: Run
        run: npm run build

      - name: Commencer
        run: npm start
